# 애플리케이션 이름을 'Shop'으로 설정합니다.
spring:
  application:
    name: Shop

  # 데이터베이스 연결을 위한 사용자 이름과 비밀번호를 설정합니다.
  datasource:
    username: root
    password: "1234"

  jpa:
    properties:
      hibernate:
        show_sql: true        # Hibernate가 실행하는 SQL 쿼리를 콘솔에 출력하도록 설정합니다.
        format_sql: true       # 출력되는 SQL 쿼리의 형식을 보기 쉽게 포맷팅합니다.
    hibernate:
      ddl-auto: create         # 애플리케이션 시작 시 데이터베이스 스키마를 새로 생성하도록 설정합니다.
    database-platform: org.hibernate.dialect.H2Dialect  # 사용 중인 데이터베이스에 맞는 Hibernate 방언을 설정합니다 (여기서는 H2 데이터베이스).

  # 파일 업로드 관련 설정
  servlet:
    multipart:
      maxFileSize: 20MB        # 파일 한 개당 최대 사이즈
      maxRequestSize: 100MB    # 요청당 최대 파일 크기

# Hibernate의 SQL 타입 변환 관련 로깅 레벨을 TRACE로 설정하여 세부 로그를 확인할 수 있습니다.
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# 상품 이미지 업로드 경로 설정
  web:
    resources:
      static-locations: classpath:/static/


productImgLocation: C:/upload/images/products